general:
   log4jfilename: configs/log4j-aggregator.properties

kafka_config:
   bootstrap.servers: <broker1:9092,broker2:9092,broker3:9092>
   state.dir: <path-to-the-state-directory>

aggregation_config:
   window.s: <period-in-seconds>
   topic.input: <input-topic>
   topic.output: <output-topic>

avg_filter:
   -   measurement: <measurement_name0>
       field.name: <field_name0>
       tags.remove: <tag_name0>
   -   measurement: <measurement_name1>
       field.name: <field_name1>,<field_name2>
       tags.remove: <tag_name1>

sum_filter:
   -   measurement: <measurement_name3>
       field.name: <field_name3>
       tags.remove: <tag_name3>,<tag_name4>
   -   measurement: <measurement_name5>
       field.name: <field_name5>

min_filter:
   -   measurement: <measurement_name0>
       field.name: <field_name0>
       tags.remove: <tag_name0>
   -   measurement: <measurement_name1>
       field.name: <field_name1>,<field_name2>
       tags.remove: <tag_name1>

max_filter:
   -   measurement: <measurement_name3>
       field.name: <field_name3>
       tags.remove: <tag_name3>,<tag_name4>
   -   measurement: <measurement_name5>
       field.name: <field_name5>

stats_config:
   enabled: true
   hostname: <infludb-hostname>
   port: <influxdb-port>
   period_ms: <sample-period-in-milliseconds>