general:
   log4jfilename: ./log4j-aggr.properties

kafka_config:
   bootstrap.servers: aido2qc41:9092,aido2qc42:9092,aido2qc43:9092
   state.dir: /mnt/data/Work/ownCloud/workspace/jpy_laptop/j_kafka_stream_aggregation/stateDir
   
aggregation:
   window_s: 30
   topic.input: aggr-avg
   topic.results: aggr-results
       
