general:
   log4jfilename: ./log4j.properties

kafka_consumer_config:
   bootstrap.servers: broker1:9092,broker2:9092,broker3:9092
   topic: notifications

mattermost_config:
   url: https://<mattermost-server-hostname>/hooks/<token-id>
   
stats_config:
   enabled: true
   type: influxdb
   hostname: <influxdb-instance-hostname>
   port: 8090
   period_ms: 10000   