general:
   log4jfilename: ./log4j.properties

topics:
   input: test3p2r
   output.avg: aggr-avg
   output.sum: aggr-sum
   output.min: aggr-min
   output.max: aggr-max
   output.default: aggr-other

kafka_config:
   bootstrap.servers: aido2qc41:9092,aido2qc42:9092,aido2qc43:9092
   
selection:
   avg:
      -   measurement: meas0
          removetags: hostname,cardid
      -   measurement: meas1
          removetags: hostname,cardid        
   min:
      -   measurement: meas2
          removetags: hostname,cardid
      -   measurement: meas3
          removetags: hostname,cardid         
   max:
      -   measurement: meas4
          removetags: hostname,cardid    
   sum:
      -   measurement: meas5
          removetags: hostname,cardid