general:
   log4jfilename: ./log4j.properties

topics:
   input: test3p2r
   output.avg: aggr-avg
   output.sum: aggr-sum
   output.min: aggr-min
   output.max: aggr-max
   output.default: aggr-other

kafka_config:
   bootstrap.servers: aido2qc41:9092,aido2qc42:9092,aido2qc43:9092
   
selection:
   avg:
      -   measurement: meas0
          tag_to_remove: hostname,cardid
      -   measurement: meas1
          tag_to_remove: hostname,cardid        
   min:
      -   measurement: meas2
          tag_to_remove: hostname,cardid
      -   measurement: meas3
          tag_to_remove: hostname,cardid         
   max:
      -   measurement: meas4
          tag_to_remove: hostname,cardid    
   sum:
      -   measurement: meas5
          tag_to_remove: hostname,cardid